config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'products#index'
  resources :products do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'paycheck'
      post'pay'
    end
    resources :comments, only: :create
  end
  resources :signups, only: [:new, :create] do
    collection do
      get 'member'
      post 'address'
      post 'telephone'
    end
  end
  
  resources :card, only: [:new, :show, :index] do
    collection do
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
  
  resources :mypage, only: [:index, :edit, :update] do
    collection do
      get 'logout', to: 'mypage#logout'
      get 'ausstellen', to: 'mypage#ausstellen'
      get 'deal', to: 'mypage#deal'
      get 'verkauf', to: 'mypage#verkauf'
      get 'profile', to: 'mypage#profile'
      get 'person', to: 'mypage#person'
      get 'addressconfirmation', to: 'mypage#addressconfirmation'
    end
  end
  resources :likes, only: [:create, :destroy, :index], defaults: { format: 'json'}
  
end

app/views/shared/shared_2/_footer-top.html.haml
.banner
  .banner__title
    だれでもかんたん、人生を変えるフリマアプリ
  .banner__subtitle
    今すぐ無料ダウンロード！
  .banner__icon
    .banner__icon__app
    .banner__icon__google  

.footer
  .footer__info
    .footer__info__furima
      FURIMAについて
    .footer__info__furima-home
      FURIMAを見る
    .footer__info__help
      ヘルプ＆ガイド
  .footer__content
    .footer__content__menu1
      会社概要（運営会社）
      プライバシーポリシー
      FURIMA利用規約
      ポイントに関する特約
    .footer__content__menu2
      カテゴリー一覧
      ブランド一覧
    .footer__content__menu3
      FURIMAガイド
      FURIMAロゴ利用ガイドライン
      お知らせ
  %div{type: "logo", class: "footer__logo", link_to: "#"}
  .footer__company-furima
    © FURIMA

app/views/shared/shared_2/_header-top.html.haml
.header
  .header__box
    .header__box__title
    = link_to image_tag("logo/logo.png", width: "150px", height: "40px"), root_path
    = form_with(url: search_products_path, local: true, method: :get, class: "header__box__search") do |form|
      = form.text_field :keyword, class: 'header__box__search__form', placeholder: 'キーワードから探す'
      = form.submit "", class: "header__box__search__btn"
  .header__box2
    .header__box2__tab
      = render partial: 'products/category-drop'
      = render partial: "products/brand-drop"
    .header__box2__info
      - if user_signed_in?
        = link_to "いいね!一覧", class: "header__box2__info__like"
        = link_to "マイページ", mypage_index_path, class: "header__box2__info__mypage"
      - else
        = link_to "ログイン", new_user_session_path, class: "header__box2__info__like"
        = link_to "新規会員登録", new_signup_path, class: "header__box2__info__mypage"

app/views/shared/shared_2/_main-top.html.haml
.content
  .content__title
    人生を変えるフリマアプリ
  .content__subtitle
    FURIMAは誰でも簡単に出品・購入できるフリマアプリです
  .content__icon
    .content__icon__app
    .content__icon__google

.content2
  .content2__title
    FURIMAが選ばれる3つの理由
  .content2__main
    .content2__main__picture
      .content2__main__picture__image1
        .content2__main__picture__image1__number
          1
      .content2__main__picture__image2
        .content2__main__picture__image2__number
          2
      .content2__main__picture__image3
        .content2__main__picture__image3__number
          3
    .content2__main__box
      .content2__main__box__text1
        3分ですぐ出品
        .content2__main__box__text1__content
          スマホで入力するだけで簡単に
          出品できる！   
      .content2__main__box__text2
        シンプルで使いやすい
        .content2__main__box__text2__content
          めんどくさい入力は必要なく、検索も
          購入もスムーズ！
      .content2__main__box__text3
        手数料が業界最安
        .content2__main__box__text3__content
          最大3%でお得に出品&購入！

.content3
  .content3__title
    会員数日本一位
  .content3__subtitle
    FURIMAは、フリマアプリで最も人気。
    出品・購入回数も業界最多です！
    ほしかったあの商品に出会えるかもしれません。
  .content3__icon
    .content3__icon__app
    .content3__icon__google

.content4
  .content4__title
    FURIMAが選ばれる3つの理由
  .content4__main
    .content4__main__picture
      .content4__main__picture__image1 
      .content4__main__picture__image2
      .content4__main__picture__image3   
    .content4__main__box
      .content4__main__box__text1
        簡単に売り買いできる
        .content4__main__box__text1__content
          スマホひとつで、いつでもどこでも簡単に
          出品・購入が可能！
      .content4__main__box__text2
        売上金は即日振込みに対応
        .content4__main__box__text2__content
          午前9時までに振込を依頼いただけれ
          ば、翌日に指定の口座に入金いたします!
      .content4__main__box__text3
        様々な支払いに対応
        .content4__main__box__text3__content
          お支払いは、クレジットカードだけでな
          く、ポイントや売上金など多彩な方法
          があります。

.content5
  .content5__main
    .content5__main__title
      ピックアップカテゴリー
      新規投稿商品
    .content5__main__picture
      .content5__main__picture__image
        - @products.each do |product|
          = link_to product_path(product), data: {"turbolinks" => false} do
            .content5__main__picture__image__content
              = image_tag product.images[0].src.url, height: "150px", width: "150px"
              .content5__main__picture__image__form  
                .content5__main__picture__image__form__name
                  = product.name
                .content5__main__picture__image__form__box
                  .content5__main__picture__image__form__box__price 
                    ¥
                    = product.price
                  .content5__main1__picture__image__form__box__like
                    %i.fa.fa-heart.redheart
                    = product.likes.length
              -if product.buyer_id.present? 
                .products-box_photo__sold
                  .products-box_photo__sold__inner
                    SOLD

app/views/shared/shared_2/_sellbtn-top.html.haml
- if user_signed_in?
  .sell_box
    出品する
    %a{type: "button", class: "sell_box__btn", href: new_product_path}