config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'products#index'
  resources :products do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'paycheck'
      post'pay'
    end
    resources :comments, only: :create
  end
  resources :signups, only: [:new, :create] do
    collection do
      get 'member'
      post 'address'
      post 'telephone'
    end
  end
  
  resources :card, only: [:new, :show, :index] do
    collection do
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
  
  resources :mypage, only: [:index, :edit, :update] do
    collection do
      get 'logout', to: 'mypage#logout'
      get 'ausstellen', to: 'mypage#ausstellen'
      get 'deal', to: 'mypage#deal'
      get 'verkauf', to: 'mypage#verkauf'
      get 'profile', to: 'mypage#profile'
      get 'person', to: 'mypage#person'
      get 'addressconfirmation', to: 'mypage#addressconfirmation'
    end
  end
  resources :likes, only: [:create, :destroy, :index], defaults: { format: 'json'}
  
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  require "payjp"
  before_action :get_payjp_info, only: [:new, :pay, :delete, :show]
  before_action :set_card, only: [:new, :show, :delete, :index]


  def index
    if @card.present?
      redirect_to card_path(@card)
    end
  end

  def new
    if @card.present?
      redirect_to card_path(@card)
    end
  end

  def pay 
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) 
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to card_path(@card)
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete 
    customer = Payjp::Customer.retrieve(@card.customer_id)
    customer.delete
    @card.delete
    redirect_to action: "new"
  end

  def show 
    if @card.blank?
      redirect_to action: "new" 
    else
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  private

  def get_payjp_info
    Payjp.api_key = Rails.application.credentials.payjp[:payjp_secret_key]
  end

  def set_card
    @card = Card.includes(:user).find_by(user_id: current_user.id)
  end

end

app/views/card/index.html.haml
= render partial: 'shared/shared_2/header-top'
.breadcrumb-bar
  - breadcrumb :payindex
  = render "layouts/breadcrumbs"
.mypageContents
  = render partial: 'mypage/side-bar'
  .credit-content
    .credit-content__title
      %h2 支払い方法
    .credit-content__create.clearfix
      .credit-content__create__info
        %h3 クレジットカード一覧
        .credit-content__create__info__add
          = link_to "クレジットカード追加する", new_card_path, class: 'credit-content__create__info__add--btn',data: {"turbolinks"=>false}
      = link_to "支払い方法について ＞", "#", class: 'credit-content__create__payhow' 

= render partial: "shared/shared_2/footer-top"

app/views/card/new.html.haml
= render partial: 'shared/shared_2/header-top'
.breadcrumb-bar
  - breadcrumb :paynew
  = render "layouts/breadcrumbs"
.mypageContents
  = render partial: 'mypage/side-bar'
  .credit-content
    .credit-content__title
      %h2 クレジットカード情報入力
    .credit-content__card
      = form_with method: :post, url: pay_card_index_path, name: "charge-form", id: 'charge-form', local: true do |f|
        .credit-content__card__number
          = f.label :カード番号,class: 'label', maxlength: "16", type: "text"
          %span.require 必須
          %br
          = f.number_field :card_nuber, type: 'text',class: 'number__text', placeholder: '半角数字のみ', id: "card_number", maxlength: "16"
          %ul
            = image_tag "credit/mastercard.svg", height: 20, width: 30
            = image_tag "credit/visa.svg", height: 20, width: 30
            = image_tag "credit/jcb.svg", height: 20, width: 30
            = image_tag "credit/dinersclub.svg", height: 20, width: 30
            = image_tag "credit/discover.svg", height: 20, width: 30
            = image_tag "credit/saison-card.svg", height: 20, width: 30
            = image_tag "credit/american_express.svg", height: 20, width: 30
        .credit-content__card__deadline
          = f.label :有効期限, class: 'label'
          %span.require 必須
          .credit-content__card__deadline__box
            = f.select :exp_month, [["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{} , class: 'input-deadline', name: "exp_month", id: "exp_month"
            %span.deadline-date 月
            = f.select :exp_year, [["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029]],{} , class: 'input-deadline', name: "exp_year", id: "exp_year"
            %span.deadline-date 年
        .credit-content__card__security
          = f.label :セキュリティーコード, class: 'label'
          %span.require 必須
          %br
          = f.number_field :cvc, type: 'text', class: 'number__text', placeholder: 'カード背面4桁もしくは3桁の番号', maxlength: "4", id: "cvc"
          .credit-content__card__security__question
            カードの裏面の番号とは？
        .credit-content__card__bottom#card_token
        = f.submit '追加する', class: 'credit-content__card__bottom--btn', id: 'token_submit'
= render partial: "shared/shared_2/footer-top"

app/views/card/show.html.haml
= render partial: 'shared/shared_2/header-top'
.breadcrumb-bar
  - breadcrumb :payshow
  = render "layouts/breadcrumbs"
.mypageContents
  = render partial: 'mypage/side-bar'
  .credit-content
    .credit-content__title
      %h2 支払い方法
    .credit-content__create.clearfix
      .credit-content__create__info
        %h3 クレジットカード一覧
        .credit-content__create__info__show
          .credit-content__create__info__show__label
            .credit-content__create__info__show__label__left
              = image_tag "credit/#{@default_card_information.brand.downcase}.svg", height: 20, width: 30
            .credit-content__create__info__show__label__right
              -# = link_to "削除する", delete_card_index_path, class: 'credit-content__create__info__show__label__right-ーbtn' 
              = form_with method: :post, url:delete_card_index_path, name: "charge-form", id: 'charge-form', local: true do |f|
                %input{ type: "hidden", name: "card_id", value: "" }
                %button.credit-content__create__info__show__label__right-btn   
                  %a 削除する
          .credit-content__create__info__show__number
            = "**** **** **** " + @default_card_information.last4
          .credit-content__create__info__show__date
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
          
      = link_to "支払い方法について ＞", "#", class: 'credit-content__create__payhow' 
= render partial: "shared/shared_2/footer-top"