config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'products#index'
  resources :products do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'paycheck'
      post'pay'
    end
    resources :comments, only: :create
  end
  resources :signups, only: [:new, :create] do
    collection do
      get 'member'
      post 'address'
      post 'telephone'
    end
  end
  
  resources :card, only: [:new, :show, :index] do
    collection do
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
  
  resources :mypage, only: [:index, :edit, :update] do
    collection do
      get 'logout', to: 'mypage#logout'
      get 'ausstellen', to: 'mypage#ausstellen'
      get 'deal', to: 'mypage#deal'
      get 'verkauf', to: 'mypage#verkauf'
      get 'profile', to: 'mypage#profile'
      get 'person', to: 'mypage#person'
      get 'addressconfirmation', to: 'mypage#addressconfirmation'
    end
  end
  resources :likes, only: [:create, :destroy, :index], defaults: { format: 'json'}
  
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  def index
    @user = User.all
  end

  def ausstellen
    @products = Product.where(saler_id: current_user.id)
  end

  def deal
  end

  def verkauf
  end

  def logout
  end

  def profile
    @user = User.all
    # @address = Address.where(current_user.id)
  end

  def person
  end

  def addressconfirmation
  end



  def edit
    @user = User.find(params[:id])
    @address = Address.find(params[:id])
  end

  def update
    @address = Address.find(params[:id])
    # binding.pry
    if @address.update(address_params)
      redirect_to mypage_index_path
    else
      render :edit
    end
  end


  private

  def address_params
    params.require(:address).permit(:send_family_name, :send_first_name, :send_family_name_kana, :send_first_name_kana, :postnumber, :prefecture_id, :city, :house_number, :building, :phonenumber)
  end
end

app/views/mypage/_side-bar.html.haml
-# = render partial: "shared/shared_2/header-top" 

.mypageContents
  %ul
    %li.page
      =link_to '/mypage' do
        マイページ
        = icon('fas', 'angle-right')
    %li
      =link_to new_product_path do
        出品する
        = icon('fas', 'angle-right')
    %li
      =link_to ausstellen_mypage_index_path do
        出品した商品-出品中
        = icon('fas', 'angle-right')
    %li
      =link_to deal_mypage_index_path do
        出品した商品ー取引中
        = icon('fas', 'angle-right')
    %li
      =link_to verkauf_mypage_index_path do
        出品した商品ー売却済
        = icon('fas', 'angle-right')
    %li
      =link_to '#' do
        購入した商品ー取引中
        = icon('fas', 'angle-right')
    %li
      =link_to '#' do
        購入した商品ー過去の取引
        = icon('fas', 'angle-right')

    %pフリペイ
    %li
      =link_to '#' do
        売上・振込申請
        = icon('fas', 'angle-right')
    %li
      =link_to '#' do
        ポイント
        = icon('fas', 'angle-right')

    %p設定
    %li 
      =link_to profile_mypage_index_path do
        プロフィール
        = icon('fas', 'angle-right')
    %li 
      =link_to edit_mypage_path(current_user.address.id) do
        発送元・住所の変更
        = icon('fas', 'angle-right')
    %li 
      =link_to card_index_path do
        支払い方法
        = icon('fas', 'angle-right')
    %li 
      =link_to '#' do
        メール・パスワード
        = icon('fas', 'angle-right')
    %li 
      =link_to person_mypage_index_path do
        本人情報
        = icon('fas', 'angle-right')
    %li 
      =link_to '#' do
        電話番号の確認
        = icon('fas', 'angle-right')
    %li.logout 
      =link_to logout_mypage_index_path do
        ログアウト
        = icon('fas', 'angle-right')

app/views/mypage/addressconfirmation.html.haml
= render partial: 'shared/shared_2/header-top'
.mypageContents
  .mypageContent
    = render partial: 'mypage/side-bar'
    .confirmationContents
      %h2発送元・住所の変更
      = form_with model: @address, local: true do |form|
        .confirmationContent
          .send_name_contents
            %label送付者名前
            .name_form
              .send_family_name_content
                =form.text_field :send_family_name, class: "send_family_form", placeholder: "例）長浜", value: current_user.address.send_family_name
                =form.text_field :send_first_name, class: "send_first_form", placeholder: "例）一矢", value: current_user.address.send_first_name
          .send_name_contents_kana
            %label送付者名前カナ
            .name_form
              .send_family_name_content_kana
                =form.text_field :send_family_name_kana, class: "send_family_form_kana", placeholder: "例）ナガハマ", value: current_user.address.send_family_name_kana
                =form.text_field :send_first_name_kana, class: "send_first_form_kana", placeholder: "例）カズヤ", value: current_user.address.send_first_name_kana
          .postnumber_contents
            %label郵便番号
            .postnumber_content
              =form.text_field :postnumber, class: "postnumber_form", placeholder: "例）111-2222", value: current_user.address.postnumber
          .prefecture_contents
            %label都道府県
            .prefecture_content
              = form.collection_select :prefecture_id, Prefecture.all, :id, :name, { :prompt => "選択してください" }, class: "active-hash", value: current_user.address.prefecture.name
          .city_contents
            %label市町村
            .city_content
              =form.text_field :postnumber, class: "city_form", placeholder: "名古屋市", value: current_user.address.city
          .housenumber_contents
            %label番地
            .housenumber_content
              =form.text_field :postnumber, class: "housenumber_form", placeholder: "番地", value: current_user.address.house_number
          .change_btn
            = form.submit "変更する", class: "change-btn"



= render partial: "shared/shared_2/footer-top"

app/views/mypage/ausstellen.html.haml
= render partial: 'shared/shared_2/header-top'
.mypageContents
  .mypageContent
    = render partial: 'mypage/side-bar'
    .ausstallencontents
      .aaa
        = link_to ausstellen_mypage_index_path, class: "waren" do
          %p出品中
      .sss
        .item
          - if @products.exists?
            - @products.each do |product|
              %p= product.name
              %p= image_tag product.images[0].src.url, class: 'status-mini-image', size: '100x100'

= render partial: "shared/shared_2/footer-top"

app/views/mypage/deal.html.haml
= render partial: 'shared/shared_2/header-top'
.mypageContents
  .mypageContent
    = render partial: 'mypage/side-bar'
    .ausstallencontents
      .aaa
        -# = link_to ausstellen_mypage_index_path, class: "waren" do
        -#   出品中
        = link_to deal_mypage_index_path, class: "waren" do
          %p取引中
        -# = link_to '#', class: "waren" do
        -#   売約済み
      .sss

= render partial: "shared/shared_2/footer-top"

app/views/mypage/edit.html.haml
= render partial: 'shared/shared_2/header-top'
.mypageContents
  .mypageContent
    = render partial: 'mypage/side-bar'
    .confirmationContents
      %h2発送元・住所の変更
      = form_with model: @address, url: mypage_path, method: :patch, local: true do |form|
        .confirmationContent
          .send_name_contents
            %label送付者名前
            .name_form
              .send_family_name_content
                =form.text_field :send_family_name, class: "send_family_form", placeholder: "例）長浜", value: current_user.address.send_family_name
                =form.text_field :send_first_name, class: "send_first_form", placeholder: "例）一矢", value: current_user.address.send_first_name
          .send_name_contents_kana
            %label送付者名前カナ
            .name_form
              .send_family_name_content_kana
                =form.text_field :send_family_name_kana, class: "send_family_form_kana", placeholder: "例）ナガハマ", value: current_user.address.send_family_name_kana
                =form.text_field :send_first_name_kana, class: "send_first_form_kana", placeholder: "例）カズヤ", value: current_user.address.send_first_name_kana
          .postnumber_contents
            %label郵便番号
            .postnumber_content
              =form.text_field :postnumber, class: "postnumber_form", placeholder: "例）111-2222", value: current_user.address.postnumber
          .prefecture_contents
            %label都道府県
            .prefecture_content
              = form.collection_select :prefecture_id, Prefecture.all, :id, :name, { :prompt => "選択してください" }, class: "active-hash", value: current_user.address.prefecture.name
          .city_contents
            %label市町村
            .city_content
              =form.text_field :city, class: "city_form", placeholder: "名古屋市", value: current_user.address.city
          .housenumber_contents
            %label番地
            .housenumber_content
              =form.text_field :house_number, class: "housenumber_form", placeholder: "番地", value: current_user.address.house_number
          .change_btn
            = form.submit "変更する", class: "change-btn"



= render partial: "shared/shared_2/footer-top"

app/views/mypage/index.html.haml
= render partial: 'shared/shared_2/header-top'
.breadcrumb-bar
  - breadcrumb :mypage
  = render "layouts/breadcrumbs"
.mypageContents
  .mypageContent
    = render partial: 'mypage/side-bar'
    .mypage
      .myphoto
        .exhibition
          =link_to profile_mypage_index_path, class: "user-nickname" do
            = current_user.nickname
          出品数 :
          -# %q.length-conunt= current_user.products.length
      .news-doing
        =link_to '#', class: "news-contents" do
          ニュース
        =link_to '#', class: "news-contents" do
          やることリスト
      .buyed-contents
        .product-content
          %h2購入した商品
          .item-doing
            =link_to '#', class: "kaufen-contents" do
              取引中
            =link_to '#', class: "kaufen-contents" do
              過去の取引


= render partial: "shared/shared_2/footer-top"

app/views/mypage/logout.html.haml
= render partial: 'shared/shared_2/header-top' 
.breadcrumb-bar
  - breadcrumb :logout
  = render "layouts/breadcrumbs"
.Mypage-logout
  .mypage-logout
    = render partial: 'mypage/side-bar'
    .logout-contents
      .logout-content
        .logout-form
          .logout-btn
            = link_to destroy_user_session_path, method: :delete do
              ログアウト
= render partial: "shared/shared_2/footer-top"

app/views/mypage/person.html.haml
= render partial: 'shared/shared_2/header-top'
.mypageContents
  .mypageContent
    = render partial: 'mypage/side-bar'
    .profileContents
      %h2本人情報
      .personcontent
        %pお客様の本人情報をご確認ください。
        %p.document登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
        = link_to '#' do
          本人確認書類のアップロードについて
          = icon('fas', 'angle-right')
      .profileContent
        .name_contents
          %labelお名前
          .name_content
            %p.family= current_user.family_name
            %p.first=current_user.first_name
        .name_kana_contents
          %labelお名前カナ
          .name_kana_content
            %p= current_user.family_name_kana
            %p.first_kana= current_user.first_name_kana
        .birthday_contents
          %label生年月日
          .birthday_content
            %p= current_user.birth_year
            %p年
            %p.birthmonth= current_user.birth_month
            %p月
            %p.birthdate= current_user.birth_date
            %p日

= render partial: "shared/shared_2/footer-top"

app/views/mypage/profile.html.haml
= render partial: 'shared/shared_2/header-top'
.mypageContents
  .mypageContent
    = render partial: 'mypage/side-bar'
    .profilecontents
      %h2プロフィール
      .profile-back
        = form_with do |form|
          .profile-picture
            .nickname_form
              =form.text_field :nickname, class: "nickname-form", placeholder: "ニックネーム", value: current_user.nickname
            .profile-text
              =form.text_area :text, class: "nickname-text", placeholder: "例）こんにちは⭐︎ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に９号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ"
            .profile_btn
              =form.submit "変更する", class: "profile-btn"


= render partial: "shared/shared_2/footer-top"

app/views/mypage/verkauf.html.haml
= render partial: 'shared/shared_2/header-top'
.mypageContents
  .mypageContent
    = render partial: 'mypage/side-bar'
    .ausstallencontents
      .aaa
        -# = link_to ausstellen_mypage_index_path, class: "waren" do
        -#   出品中
        -# = link_to deal_mypage_index_path, class: "waren" do
        -#   %p取引中
        = link_to '#', class: "waren" do
          %p売約済
      .sss

= render partial: "shared/shared_2/footer-top"