config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'products#index'
  resources :products do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'paycheck'
      post'pay'
    end
    resources :comments, only: :create
  end
  resources :signups, only: [:new, :create] do
    collection do
      get 'member'
      post 'address'
      post 'telephone'
    end
  end
  
  resources :card, only: [:new, :show, :index] do
    collection do
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
  
  resources :mypage, only: [:index, :edit, :update] do
    collection do
      get 'logout', to: 'mypage#logout'
      get 'ausstellen', to: 'mypage#ausstellen'
      get 'deal', to: 'mypage#deal'
      get 'verkauf', to: 'mypage#verkauf'
      get 'profile', to: 'mypage#profile'
      get 'person', to: 'mypage#person'
      get 'addressconfirmation', to: 'mypage#addressconfirmation'
    end
  end
  resources :likes, only: [:create, :destroy, :index], defaults: { format: 'json'}
  
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :images, dependent: :destroy, index_errors: true
  accepts_nested_attributes_for :images, allow_destroy: true
  belongs_to :user, optional: true
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  has_many :comments
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :delivarydate
  belongs_to_active_hash :status
  belongs_to_active_hash :shippingcharges, optional: true
  belongs_to :category, optional: true
  validates :images,:name,:price,:description,:status_id,:delivery_date_id,:prefecture_id,:shopping_charge_id,:categories_id,:saler_id,presence: true
  validates :categories_id, numericality: { only_integer: true}


  def self.search(search)
    return Product.all unless search
    Product.where(['name LIKE ?', "%#{search}%"])
  end
  
  def like?(user)
    like_users.include?(user)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :update, :destroy,:show, :paycheck, :pay]
  before_action :set_categories, only: [:new, :create, :edit, :update]
  before_action :set_card, only: [:paycheck, :pay]
  require "payjp"

  def index
    @products = Product.includes(:images).order('created_at DESC').limit(10)
  end
  def show
    @saler_user = User.find(@product.saler_id)
    @category = Category.find(@product.categories_id)
    @shopping = Shippingcharges.find(@product.shopping_charge_id)
    @delivery_date = Delivarydate.find(@product.delivery_date_id)
    @comment = Comment.new
    @comments = @product.comments.includes(:user)
    if user_signed_in?
      set_card
    end
  end  

  def new
    @product = Product.new
    @product.images.new  

    def get_category_children
      @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
    end

    def get_category_grandchildren
      @category_grandchildren = Category.find("#{params[:child_id]}").children
    end
  end

  def create
    @product = Product.new(product_params)
    @product.saler_id = current_user.id
    begin 
      @product.save!
      redirect_to root_path
    rescue => e
      p e
      session[:error] = @product.errors.full_messages
      redirect_to new_product_path
    end
  end

  def edit
    @productCategory = Category.find(@product.categories_id)
    @childCategory = @productCategory.parent
    @rootCategory = @productCategory.root
    @category_children = [@childCategory] 
    @rootCategory.children.each do |child|
      if child.name === @childCategory.name
        child.name = "---"
        child.id = "-"
      end
      @category_children << child
    end
    @category_parent_array = [@rootCategory.name]
    Category.where(ancestry: nil).each do |parent|
      if parent.name === @rootCategory.name
        parent.name = "---"
      end
      @category_parent_array << parent.name
    end
    @category_grandchildren_array = [@productCategory]
    @childCategory.children.each do |grandchild|
      if grandchild.name === @productCategory.name
        grandchild.name = "---"
      end
      @category_grandchildren_array << grandchild
    end
    def get_category_children
      #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
      @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
    end

    def get_category_grandchildren
      #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
      @category_grandchildren = Category.find("#{params[:child_id]}").children
    end
    @images = @product.images
    if @images.empty?
      @product.images.new
    end
  end

  def update
    @productCategory = Category.find_by(name:params[:categories_id])
    @product.categories_id = @productCategory
    if @product.update(product_params)
      redirect_to root_path
    else
      redirect_to edit_product_path(@product.id)
    end
  end

  def destroy
    if @product.destroy
      redirect_to root_path
    else
      render :show
    end
  end



  def paycheck
    if @card.blank?
      redirect_to controller: "card", action: "new"
    else
      Payjp.api_key = Rails.application.credentials.payjp[:payjp_secret_key]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  def pay
    Payjp.api_key = Rails.application.credentials.payjp[:payjp_secret_key]
    Payjp::Charge.create(
    amount:  @product.price,
    customer:  @card.customer_id,
    currency: 'jpy'
  )
  @product_buyer = Product.find(params[:id])
  @product_buyer.update( buyer_id: current_user.id)
  redirect_to root_path
  end

  def search
    @products = Product.search(params[:keyword]).order('created_at DESC').limit(5)
  end

  private

  
  def product_params
    params.require(:product).permit(:name, :price, :description, :status_id, :delivery_date_id, :shopping_charge_id,:categories_id, :prefecture_id,:bland, images_attributes: [:src, :_destroy, :id,:croped_image])
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def set_categories
    @category_parent_array = ["---"]
    #データベースから、親カテゴリーのみ抽出し、配列化
    Category.where(ancestry: nil).each do |parent|
        @category_parent_array << parent.name
    end
  end

  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end

end

app/views/products/_brand-drop.html.haml
%ul.ddmenu
  %li
    %a{:href => "#"} ブランド
    %ul
      %li
        %a{:href => "#"} シャネル
        %a{:href => "#"} ナイキ
        %a{:href => "#"} ルイ ヴィトン
        %a{:href => "#"} シュプリーム
        %a{:href => "#"} アディダス
        %a{:href => "#"} ブランド一覧

app/views/products/_form.html.haml
.container
  = form_for @product do |f|
    .head
      %h2 商品情報入力
    .section.clearfix
      %label
        画像投稿
        %span
          必須
      %p
        最大10枚までアップロードできます。
      .image-input__box#image-box
        #previews
          %ul.prev
            - if @product.persisted?
              - @product.images.each_with_index do |image, i|
                %li.previews__box
                  = image_tag image.src.url, data: { index: i }, width: "100", height: '120'
                  .btn-box
                    .js-change 編集
                    .js-remove 削除
          .drop-zone.input-box
            .js-file_group{"data-index" => "#{@product.images.count}"}
              %label{:for => "product_images_attributes_#{@product.images.count}_src"}
                %p
                  ドラッグアンドドロップ
                  %br/
                  またはクリックしてファイルをアップロード
                = file_field_tag "product_images_attributes_#{@product.images.count}_src", name: "product[images_attributes][#{@product.images.count}][src]", class: 'js-file'
        = f.fields_for :images do |image|
          .drop-zone{:style => "display:none;"}
            .js-file_group{"data-index" => "#{image.index}"}
              %label{:for => "product_images_attributes_#{image.index}_src"}
                %p
                  ドラッグアンドドロップ
                  %br/
                  またはクリックしてファイルをアップロード
                = image.file_field :src, class: 'js-file'
            = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'
            %br/
      .field_with_errors
        - if session[:error].present?
          %ul.errors
            - session[:error].each do |e|
              - if e.include?("src")
                %li.error 
                  画像がありません
          
    .section
      .form
        %label 
          商品名
          %span
            必須
        = f.text_field :name,{:type => "text",:placeholder => "商品名（必須 40文字まで)"}
        .field_with_errors
          - if session[:error].present?
            %ul.errors
              - session[:error].each do |e|
                - if e.include?("名前")
                  %li.error 
                    商品名がありません
        .form__group
          %label 
            商品の説明
            %span
              必須
          = f.text_area :description,{:placeholder => "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"}
          .field_with_errors
            - if session[:error].present?
              %ul.errors
                - session[:error].each do |e|
                  - if e.include?("説明")
                    %li.error 
                      説明がありません
    .section
      .select.clearfix
        %h3 商品の詳細
        .select__box.listing-form-box
          %label.listing-product-detail__category
            カテゴリー
            %span.listing-default--require
              必須

            - if @product.persisted?
              .listing-select-wrapper
                .listing-select-wrapper__box.select-wrap
                  = f.select :categories_id, @category_parent_array, {}, {class: 'listing-select-wrapper__box--select', id: 'parent_category'}
                  .listing-select-wrapper__added#children_wrapper
                    .listing-select-wrapper__box.select-wrap
                      = f.select :categories_id, options_for_select(@category_children.map{|c|[c[:name], data: {category: c[:id]}]}), {}, {class: 'listing-select-wrapper__box--select', id: 'child_category'}
                  .listing-select-wrapper__added#grandchildren_wrapper
                    .listing-select-wrapper__box.select-wrap
                      = f.select :categories_id, options_for_select(@category_grandchildren_array.map{|c|[c[:name], c[:id]]}), {}, {class: 'listing-select-wrapper__box--select', id: 'id="grandchild_category"'}
            -if @product.new_record?
              .listing-select-wrapper
                .listing-select-wrapper__box.select-wrap
                  %i.fa.fa-chevron-down
                  = f.select :categories_id, @category_parent_array, {}, {class: 'listing-select-wrapper__box--select', id: 'parent_category'}
          .field_with_errors
            - if session[:error].present?
              %ul.errors
                - session[:error].each do |e|
                  - if e.include?("カテゴリー")
                    .error 
                      カテゴリーを選択してください
          
        .select__box
          %label 
            商品の状態
            %span
              必須
          .select-wrap
            %i.fa.fa-chevron-down
            = f.collection_select :status_id, Status.all, :id, :name, prompt: "--", class: 'input'
            .field_with_errors
              - if session[:error].present?
                %ul.errors
                  - session[:error].each do |e|
                    - if e.include?("状態")
                      %li.error 
                        商品の状態が選択されていません
          .select__box
            %label 
              ブランド
              %span
                任意
            .select-wrap
              = f.text_field :bland,{:type => "text",:placeholder => "例)　タニタ"}
    .section
      .select.clearfix
        %h3 配送について
        %a.form-question ?
        .select__box
          %label 
            配送料の負担
            %span
              必須
          .select-wrap
            %i.fa.fa-chevron-down
            = f.collection_select :shopping_charge_id, Shippingcharges.all, :id, :name, prompt: "--", class: 'input'
          .field_with_errors
            - if session[:error].present?
              %ul.errors
                - session[:error].each do |e|
                  - if e.include?("配送料")
                    %li.error 
                      配送料の負担を選んでください
        .select__box
          %label 
            発送元の地域
            %span
              必須
          .select-wrap
            %i.fa.fa-chevron-down
            = f.collection_select :prefecture_id, Prefecture.all, :id, :name, prompt: "--", class: 'input'
          .field_with_errors
            - if session[:error].present?
              %ul.errors
                - session[:error].each do |e|
                  - if e.include?("地域")
                    %li.error 
                      発送元の地域を選んでください
        .select__box
          %label 
            発送までの日数
            %span
              必須
          .select-wrap
            %i.fa.fa-chevron-down
            = f.collection_select :delivery_date_id, Delivarydate.all, :id, :name, prompt: "--", class: 'input'
          .field_with_errors
            - if session[:error].present?
              %ul.errors
                - session[:error].each do |e|
                  - if e.include?("配送日")
                    %li.error 
                      配送日を選択してください

    .section
      .clearfix
        %h3 販売価格(300〜9,999,999)
        %a.form-question ?
        .sell-form-box
          %ul.sell-price
            %li.form-group
              .clearfix
                .l-left
                  %label 
                    価格
                    %span
                      必須
                .l-right
                  .yen ¥
                  = f.telephone_field :price, {:placeholder => "例）300"}
              .field_with_errors
                - if session[:error].present?
                  %ul.errors
                    - session[:error].each do |e|
                      - if e.include?("価格")
                        .error 
                          価格がありません
                          - session[:error] = nil
            %li.clearfix.list
              %p.l-left  販売手数料 (10%)
              %p.l-right#commision  -
            %li.bold.list
              .clearfix
                %p.l-left 販売利益
                %p.l-right#profit -
    .section
      .sell-btn-box.clearfix
        %p
          %a 禁止されている出品、
          %a 行為
          を必ずご確認ください。
        %p
          またブランド品でシリアルナンバー等がある場合はご記載ください。
          %a 偽ブランドの販売
          は犯罪であり処罰される可能性があります。
        %p
          また、出品をもちまして
          %a 加盟店規約
          に同意したことになります。

        = f.submit '出品する', class: "btn-default btn-blue"
        %a.btn-default.btn-gray 戻る
-# ↓本番環境でcategory.jsがうまく機能せず解決策を探した結果hamlファイルに直書きで解消できるとのことだったので直書き
:javascript
    $(function(){
    // カテゴリーセレクトボックスのオプションを作成
    function appendOption(category){
      var html = `<option value="${category.id}" data-category="${category.id}">${category.name}</option>`;
      return html;
    }
    function appendChildOption(category){
      var html = `<option value="${null}" data-category="${category.id}">${category.name}</option>`;
      return html;
    }
    // 子カテゴリーの表示作成
    function appendChidrenBox(insertHTML){
      var childSelectHtml = '';
      childSelectHtml = `<div class='listing-select-wrapper__added' id= 'children_wrapper'><div class="select-wrap"><i class='fas fa-chevron-down listing-select-wrapper__box--arrow-down'></i>
                          <div class='listing-select-wrapper__box'>
                            <select class="listing-select-wrapper__box--select" id="child_category" name="product[categories_id]">
                              <option value="${null}" data-category="---">---</option>
                              ${insertHTML}
                            <select>
                            </div>
                          </div>
                        </div>`;
      $('.listing-product-detail__category').append(childSelectHtml);
    }
    // 孫カテゴリーの表示作成
    function appendGrandchidrenBox(insertHTML){
      var grandchildSelectHtml = '';
      grandchildSelectHtml = `<div class='listing-select-wrapper__added' id= 'grandchildren_wrapper'>
                                <div class='listing-select-wrapper__box'><div class="select-wrap">
                                  <i class='fas fa-chevron-down listing-select-wrapper__box--arrow-down'></i>
                                  <select class="listing-select-wrapper__box--select" id="grandchild_category" name="product[categories_id]">
                                    <option value="---" data-category="---">---</option>
                                    ${insertHTML}
                                  </select>
                                  
                                  </div>
                                </div>
                              </div>`;
      $('.listing-product-detail__category').append(grandchildSelectHtml);
    }
    // 親カテゴリー選択後のイベント
    $('#parent_category').on('change', function(){
      var parentCategory = $('#parent_category').val(); //選択された親カテゴリーの名前を取得
      if (parentCategory != "---"){ //親カテゴリーが初期値でないことを確認
        $.ajax({
          url: 'get_category_children',
          type: 'GET',
          data: { parent_name: parentCategory },
          dataType: 'json'
        })
        .done(function(children){
          $('#children_wrapper').remove(); //親が変更された時、子以下を削除するする
          $('#grandchildren_wrapper').remove();
          $('#size_wrapper').remove();
          $('#brand_wrapper').remove();
          var insertHTML = '';
          children.forEach(function(child){
            insertHTML += appendChildOption(child);
          });
          appendChidrenBox(insertHTML);
        })
        .fail(function(){
          alert('カテゴリー取得に失敗しました');
        })
      }else{
        $('#children_wrapper').remove(); //親カテゴリーが初期値になった時、子以下を削除するする
        $('#grandchildren_wrapper').remove();
        $('#size_wrapper').remove();
        $('#brand_wrapper').remove();
      }
    });
    // 子カテゴリー選択後のイベント
    $('.listing-product-detail__category').on('change', '#child_category', function(){
      var childId = $('#child_category option:selected').data('category'); //選択された子カテゴリーのidを取得
      if (childId != "---"){ //子カテゴリーが初期値でないことを確認
        $.ajax({
          url: 'get_category_grandchildren',
          type: 'GET',
          data: { child_id: childId },
          dataType: 'json'
        })
        .done(function(grandchildren){
          if (grandchildren.length != 0) {
            $('#grandchildren_wrapper').remove(); //子が変更された時、孫以下を削除するする
            $('#size_wrapper').remove();
            $('#brand_wrapper').remove();
            var insertHTML = '';
            grandchildren.forEach(function(grandchild){
              insertHTML += appendOption(grandchild);
            });
            appendGrandchidrenBox(insertHTML);
          }
        })
        .fail(function(){
          alert('カテゴリー取得に失敗しました');
        })
      }else{
        $('#grandchildren_wrapper').remove(); //子カテゴリーが初期値になった時、孫以下を削除する
        $('#size_wrapper').remove();
        $('#brand_wrapper').remove();
      }
    });
  });

app/views/products/_products.html.haml
= render 'likes/like_links', product: @product

app/views/products/edit.html.haml
.wrapper
  = render partial: "shared/shared_1/header"
  =render partial: "form"
  = render partial: "shared/shared_1/footer"

app/views/products/index.html.haml
.top-page
  = render partial: 'shared/shared_2/header-top'
  = render partial: 'shared/shared_2/main-top'
  = render partial: 'shared/shared_2/footer-top'
  = render partial: 'shared/shared_2/sellbtn-top'

app/views/products/new.html.haml
.wrapper
  = render partial: "shared/shared_1/header"
  =render partial: "form"
  = render partial: "shared/shared_1/footer"

app/views/products/paycheck.html.haml
.wrapper
  = render partial: "shared/shared_1/header"
.purchase-contents
  .purchase-content
    .purchase-content__header
      購入内容の確認
    .purchase-content__item
      .purchase-content__item__box
        .purchase-content__item__box__img
          = image_tag @product.images[0].src.url,height: "80px", width: "80px"
        .purchase-content__item__box__show
          .purchase-content__item__box__show__name
            商品名
          .purchase-content__item__box__show__label
            .purchase-content__item__box__show__label__price
              %a ¥
              = @product.price
            .purchase-content__item__box__show__label__tax
              （税込）送料込み
    .purchase-content__info
      .purchase-content__info__price
        .purchase-content__info__price__name
          .purchase-content__info__price__name__pay
            支払い金額
          .purchase-content__info__price__name__count
            %a ¥ 
            = @product.price
        .purchase-content__info__price__point
          .purchase-content__info__price__point__icon
          .purchase-content__info__price__point__name
            ポイントを使用（所持ポイント:P0)
      .purchase-content__info__credit
        .purchase-content__info__credit__how
          .purchase-content__info__credit__how__left
            支払い方法
          .purchase-content__info__credit__how__right
            = link_to root_path,class:"purchase-content__info__credit__how__right--link" do
              変更する
        .purchase-content__info__credit__card
          %p クレジットカード
          - if @default_card_information.blank?
            %br /
          - else
            = "**** **** **** " + @default_card_information.last4
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
            %br
        .purchase-content__info__credit__img
          = image_tag "credit/mastercard.svg", height: 20, width: 34
      .purchase-content__info__address
        .purchase-content__info__address__send
          .purchase-content__info__address__send__left
            配送先
          .purchase-content__info__address__send__right
            = link_to root_path,class:"purchase-content__info__address__send__right--link" do
              変更する
        .purchase-content__info__address__area
          %a 〒
          = @current_user.address.postnumber
          %br
          = @current_user.address.prefecture.name
          = @current_user.address.city
          %br
          = @current_user.family_name
          = @current_user.first_name
      .purchase-content__info__purchase-btn
      = form_with method: :post, url:pay_product_path, local: true do |f|
        = f.submit '購入する', class: "purchase-content__info__purchase-btn__box"
      -# = form_tag(action: :pay, method: :post) do
      -#   %button.purchase-content__info__purchase-btn__box 購入する

  = render partial: "shared/shared_1/footer"

app/views/products/search.html.haml
.search
  = render partial: 'shared/shared_2/header-top'
  .search-contents
    .content5__main__picture
      .content5__main__picture__image
        - @products.each do |product|
          = link_to product_path(product), data: {"turbolinks" => false} do
            .content5__main__picture__image__content
              = image_tag product.images[0].src.url, height: "150px", width: "150px"
              .content5__main__picture__image__form  
                .content5__main__picture__image__form__name
                  = product.name
                .content5__main__picture__image__form__box
                  .content5__main__picture__image__form__box__price 
                    ¥
                    = product.price
                  .content5__main__picture__image__form__box__like
                    ☆1
              -if product.buyer_id.present? 
                .products-box_photo__sold
                  .products-box_photo__sold__inner
                    SOLD
  = render partial: 'shared/shared_2/footer-top'
  = render partial: 'shared/shared_2/sellbtn-top'

app/views/products/show.html.haml
.products-detail
  = render partial: "shared/shared_2/header-top"
  .breadcrumb-bar
    - breadcrumb :show, @product
    = render "layouts/breadcrumbs"
.content-detail
  .content-detail__form
    .content-detail__form__title
      = @product.name
    .content-detail__form__box
      .content-detail__form__box__image
        .slick  
          - @product.images.each do |product_image|
            - if product_image.croped_image.blank?
              = image_tag product_image.src.url, class: "slick-img", height: "300px", width: "300px"
            - else
              = image_tag product_image.croped_image, class: "slick-img", height: "300px", width: "300px"
        .slick-thumbnail
          - @product.images.each do |product_image|
            - if product_image.croped_image.blank?
              = image_tag product_image.src.url, class: "slick-thumbnail_item", height: "60px", width: "60px"
            - else
              = image_tag product_image.croped_image, class: "slick-img", height: "300px", width: "300px"
        -if @product.buyer_id.present? 
          .products-box_show_photo__sold
            .products-box_show_photo__sold__inner
              SOLD
      .content-detail__form__box__detail
        .content-detail__form__box__detail__seller
          出品者
        .content-detail__form__box__detail__seller__form
          = @saler_user.nickname
        .content-detail__form__box__detail__category
          カテゴリー
        .content-detail__form__box__detail__category__form
          = @category.root.name
          = "> #{@category.parent.name}"
          = "> #{@category.name}"
        .content-detail__form__box__detail__brand
          ブランド
        .content-detail__form__box__detail__brand__form
          = @product.bland
        .content-detail__form__box__detail__size
          商品のサイズ
        .content-detail__form__box__detail__size__form
          指定なし
        .content-detail__form__box__detail__status
          商品の状態
        .content-detail__form__box__detail__status__form
          = @product.status.name
        .content-detail__form__box__detail__delivery-price
          配送料の負担
        .content-detail__form__box__detail__delivery-price__form
          = @shopping.name
        .content-detail__form__box__detail__delivery-method
          配送の方法
        .content-detail__form__box__detail__delivery-method__form
          佐川急便
        .content-detail__form__box__detail__delivery-origin
          配送元の地域
        .content-detail__form__box__detail__delivery-origin__form
          = @product.prefecture.name
        .content-detail__form__box__detail__delivery-date
          発送日の目安
        .content-detail__form__box__detail__delivery-date__form
          = @delivery_date.name
    .content-detail__form__price
      .content-detail__form__price__bold
        = "¥ #{@product.price}"
      .content-detail__form__price__item
        .content-detail__form__price__item__tax
          (税込)
        -if @product.shopping_charge_id == 1
          .content-detail__form__price__item__delivery-price
            送料込み
        -else
          .content-detail__form__price__item__delivery-price
            着払い    
    - if user_signed_in?
      - if current_user.id == @product.saler_id
        = link_to "編集画面にすすむ", edit_product_path, class: "content-detail__form__edit-btn"
        = link_to "商品を削除する", @product, method: :delete, class: "content-detail__form__destroy"
      - else
        -if @product.buyer_id.present?
          .content-detail__form__sold-btn
            売り切れました
        -else
          - if @card.present?
            = link_to "購入画面にすすむ",paycheck_product_path, class: 'content-detail__form__bay-btn',data: {"turbolinks"=>false}
          - else
            = link_to "支払い情報を登録をしてください",new_card_path, class: 'content-detail__form__bay-btn',data: {"turbolinks"=>false}
    - else
      = link_to "ログインしてください", new_user_session_path, class: "content-detail__form__destroy"
    .content-detail__form__description
      = @product.description
    .content-detail__form__icon
      .content-detail__form__icon__like.like
        %a いいね！
        - if user_signed_in?
          - if @product.like?(current_user)
            %i.fa.fa-heart.heart{data:{ids:{"product": @product.id,"user": current_user.id}}}
          - else
            %i.fa.fa-heart{data:{ids:{"product": @product.id,"user": current_user.id}}}
          %a#likes-count
            = @product.likes.length
        - else
          - if @product.likes.length > 0
            %i.fa.fa-heart.heart
            = @product.likes.length
          - else
            %i.fa.fa-heart
            = @product.likes.length

      .content-detail__form__icon__report
        不適切な商品の報告
    .comments
      %h4 < コメント一覧 >
      .comment
        -if @comments
          -@comments.reverse.each do |comment|
            .comment-name
              =link_to comment.user.nickname 
              -# %p :
              .baloon-left
                %p.product-comment=comment.text
  .content-detail__comment
    -if current_user
      = form_with model: @comment, id: "new-form", url: product_comments_path(@product), method: :post, local: true do |form|
        .content-detail__comment__danger
          相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。 
        .content-detail__comment__form
          =form.text_area :text, placeholder: "例）こんばんは！  こちらの商品は大変素晴らしいと思ったのですが、、、価格と釣り合っていないように思われます！！  もしかしたら他の方が不快感を覚えるかもしれないので（僕は思わないですけど、、）、取り下げられた方が良いのではないかと愚考します。", class: "comment-area", id: "area"  
        .content-detail__comment__btn  
          =form.submit "コメントする", class: "comment-btn", id: "btn"
        -# -binding.pry
    -else
      %p※※ コメントの投稿には新規登録/ログインが必要です ※※
  
= render partial: "shared/shared_2/footer-top"

:javascript
    $(function() {
      $(document).on("click","i",function() {
        var product = $(this).data("ids-product");
        var user = $(this).data("ids-user");
        let count = $('#likes-count').text().trim();
        console.log(+count + 1);
        if($(this).hasClass('heart')){
          $.ajax({
          type: 'DELETE',
          url: `/likes/${product}`,
          data: {product_id: product, user_id: user},
          dataType: 'json'
        })
        .done(function(){
          console.log('成功');
          $('.fa-heart').removeClass('heart');
          $('#likes-count').empty();
          $('#likes-count').append(+count - 1);
        })
        .fail(function(){
          console.log('失敗');
        });
        }else{
          $.ajax({
          type: 'POST',
          url: "/likes",
          data: {product_id: product},
          dataType: 'json'
          })
        .done(function(){
          console.log('成功');
          $('.fa-heart').addClass('heart');
          $('#likes-count').empty();
          $('#likes-count').append(+count + 1);
        })
        .fail(function(){
          console.log('失敗');
        });
        }
      });
    });